whenever sqlerror exit sql.sqlcode rollback

create table project (
    project_id          number generated by default as identity primary key,
    project_code        varchar2(20) not null,
    application_name    varchar2(100) not null,
    description         varchar2(1000),
    owner_name          varchar2(100),
    sme_name            varchar2(100),
    manager_name        varchar2(100),
    support_url         varchar2(500),
    active_flag         char(1) default 'Y' not null,
    constraint uk_project_code unique (project_code),
    constraint ck_project_active check (active_flag in ('Y','N'))
);

create table environment (
    environment_id      number generated by default as identity primary key,
    environment_code    varchar2(20) not null,
    display_name        varchar2(100) not null,
    sort_order          number,
    constraint uk_environment_code unique (environment_code)
);

create table db_cluster (
    cluster_id          number generated by default as identity primary key,
    cluster_name        varchar2(100) not null,
    platform_type       varchar2(30) not null,
    description         varchar2(500),
    constraint uk_cluster_name unique (cluster_name)
);

create table cluster_node (
    node_id             number generated by default as identity primary key,
    cluster_id          number not null,
    node_name           varchar2(100) not null,
    active_flag         char(1) default 'Y' not null,
    constraint fk_node_cluster foreign key (cluster_id) references db_cluster(cluster_id),
    constraint uk_cluster_node unique (cluster_id, node_name),
    constraint ck_node_active check (active_flag in ('Y','N'))
);

create table database_inventory (
    database_id         number generated by default as identity primary key,
    database_name       varchar2(30) not null,
    environment_id      number not null,
    cluster_id          number,
    architecture_type   varchar2(20) not null,
    database_role       varchar2(20) not null,
    oracle_version      varchar2(30),
    description         varchar2(500),
    active_flag         char(1) default 'Y' not null,
    constraint uk_database_name unique (database_name),
    constraint fk_db_environment foreign key (environment_id) references environment(environment_id),
    constraint fk_db_cluster foreign key (cluster_id) references db_cluster(cluster_id),
    constraint ck_db_architecture check (architecture_type in ('SINGLE','RAC')),
    constraint ck_db_role check (database_role in ('PRIMARY','STANDBY','NONE')),
    constraint ck_db_active check (active_flag in ('Y','N'))
);

create table database_project (
    database_id         number not null,
    project_id          number not null,
    primary_flag        char(1) default 'N' not null,
    constraint pk_database_project primary key (database_id, project_id),
    constraint fk_dbproj_database foreign key (database_id) references database_inventory(database_id),
    constraint fk_dbproj_project foreign key (project_id) references project(project_id),
    constraint ck_dbproj_primary check (primary_flag in ('Y','N'))
);

create table db_account (
    account_id          number generated by default as identity primary key,
    database_id         number not null,
    account_name        varchar2(128) not null,
    account_type        varchar2(20) not null,
    account_status      varchar2(30) not null,
    last_password_change date,
    description         varchar2(500),
    constraint fk_account_database foreign key (database_id) references database_inventory(database_id),
    constraint uk_db_account unique (database_id, account_name),
    constraint ck_account_type check (account_type in ('SCHEMA','USER','SERVICE','DBLINK','SHARED'))
);

create table account_project (
    account_id          number not null,
    project_id          number not null,
    primary_flag        char(1) default 'Y' not null,
    constraint pk_account_project primary key (account_id, project_id),
    constraint fk_acctproj_account foreign key (account_id) references db_account(account_id),
    constraint fk_acctproj_project foreign key (project_id) references project(project_id),
    constraint ck_acctproj_primary check (primary_flag in ('Y','N'))
);

create table db_service (
    service_id          number generated by default as identity primary key,
    database_id         number not null,
    service_name        varchar2(128) not null,
    enabled_flag        char(1) default 'Y' not null,
    constraint fk_service_database foreign key (database_id) references database_inventory(database_id),
    constraint uk_db_service unique (database_id, service_name),
    constraint ck_service_enabled check (enabled_flag in ('Y','N'))
);

create table service_node_expectation (
    service_id          number not null,
    node_id             number not null,
    expected_flag       char(1) default 'Y' not null,
    observed_flag       char(1) default 'N' not null,
    constraint pk_service_node primary key (service_id, node_id),
    constraint fk_svcn_service foreign key (service_id) references db_service(service_id),
    constraint fk_svcn_node foreign key (node_id) references cluster_node(node_id),
    constraint ck_svcn_expected check (expected_flag in ('Y','N')),
    constraint ck_svcn_observed check (observed_flag in ('Y','N'))
);

create table dr_relationship (
    dr_relationship_id  number generated by default as identity primary key,
    primary_database_id number not null,
    standby_database_id number not null,
    protection_mode     varchar2(30),
    transport_status    varchar2(30),
    apply_status        varchar2(30),
    constraint fk_dr_primary foreign key (primary_database_id) references database_inventory(database_id),
    constraint fk_dr_standby foreign key (standby_database_id) references database_inventory(database_id),
    constraint uk_dr_pair unique (primary_database_id, standby_database_id),
    constraint ck_dr_distinct check (primary_database_id <> standby_database_id)
);

create table patch_group (
    patch_group_id      number generated by default as identity primary key,
    patch_group_name    varchar2(100) not null,
    target_ru           varchar2(30) not null,
    maintenance_window  varchar2(100),
    constraint uk_patch_group_name unique (patch_group_name)
);

create table database_patch_schedule (
    database_id         number not null,
    patch_group_id      number not null,
    scheduled_date      date,
    completion_date     date,
    status              varchar2(20) default 'PLANNED' not null,
    constraint pk_db_patch_schedule primary key (database_id, patch_group_id),
    constraint fk_patch_database foreign key (database_id) references database_inventory(database_id),
    constraint fk_patch_group foreign key (patch_group_id) references patch_group(patch_group_id),
    constraint ck_patch_status check (status in ('PLANNED','READY','COMPLETE','DEFERRED','FAILED'))
);

create table standard_exception (
    exception_id        number generated by default as identity primary key,
    database_id         number,
    exception_type      varchar2(50) not null,
    description         varchar2(1000) not null,
    justification       varchar2(1000) not null,
    approved_by         varchar2(100),
    review_date         date,
    active_flag         char(1) default 'Y' not null,
    constraint fk_exception_database foreign key (database_id) references database_inventory(database_id),
    constraint ck_exception_active check (active_flag in ('Y','N'))
);
