whenever sqlerror exit sql.sqlcode rollback

create table project (
    project_id          number generated by default as identity primary key,
    project_code        varchar2(20) not null,
    application_name    varchar2(100) not null,
    description         varchar2(1000),
    owner_name          varchar2(100),
    sme_name            varchar2(100),
    manager_name        varchar2(100),
    support_url         varchar2(500),
    active_flag         char(1) default 'Y' not null,
    constraint uk_project_code unique (project_code),
    constraint ck_project_active check (active_flag in ('Y','N'))
);

create table environment (
    environment_id      number generated by default as identity primary key,
    environment_code    varchar2(20) not null,
    display_name        varchar2(100) not null,
    sort_order          number,
    constraint uk_environment_code unique (environment_code)
);

create table db_cluster (
    cluster_id          number generated by default as identity primary key,
    cluster_name        varchar2(100) not null,
    platform_type       varchar2(30) not null,
    description         varchar2(500),
    constraint uk_cluster_name unique (cluster_name)
);

create table cluster_node (
    node_id             number generated by default as identity primary key,
    cluster_id          number not null,
    node_name           varchar2(100) not null,
    active_flag         char(1) default 'Y' not null,
    constraint fk_node_cluster foreign key (cluster_id) references db_cluster(cluster_id),
    constraint uk_cluster_node unique (cluster_id, node_name),
    constraint ck_node_active check (active_flag in ('Y','N'))
);

create table cdb (
    cdb_id              number generated by default as identity primary key,
    cdb_name            varchar2(30) not null,
    db_unique_name      varchar2(30) not null,
    cluster_id          number,
    architecture_type   varchar2(20) not null,
    database_role       varchar2(20) not null,
    oracle_version      varchar2(30),
    description         varchar2(500),
    active_flag         char(1) default 'Y' not null,
    constraint uk_cdb_name unique (cdb_name),
    constraint uk_cdb_unique_name unique (db_unique_name),
    constraint fk_cdb_cluster foreign key (cluster_id) references db_cluster(cluster_id),
    constraint ck_cdb_architecture check (architecture_type in ('SINGLE','RAC')),
    constraint ck_cdb_role check (database_role in ('PRIMARY','STANDBY','NONE')),
    constraint ck_cdb_active check (active_flag in ('Y','N'))
);

create table db_instance (
    instance_id         number generated by default as identity primary key,
    cdb_id              number not null,
    node_id             number not null,
    instance_name       varchar2(30) not null,
    instance_number     number not null,
    status              varchar2(20),
    active_flag         char(1) default 'Y' not null,
    constraint fk_instance_cdb foreign key (cdb_id) references cdb(cdb_id),
    constraint fk_instance_node foreign key (node_id) references cluster_node(node_id),
    constraint uk_cdb_instance_name unique (cdb_id, instance_name),
    constraint uk_cdb_instance_number unique (cdb_id, instance_number),
    constraint ck_instance_active check (active_flag in ('Y','N'))
);

create table pdb (
    pdb_id              number generated by default as identity primary key,
    cdb_id              number not null,
    environment_id      number not null,
    pdb_name            varchar2(30) not null,
    open_mode           varchar2(30),
    description         varchar2(500),
    active_flag         char(1) default 'Y' not null,
    constraint fk_pdb_cdb foreign key (cdb_id) references cdb(cdb_id),
    constraint fk_pdb_environment foreign key (environment_id) references environment(environment_id),
    constraint uk_cdb_pdb_name unique (cdb_id, pdb_name),
    constraint ck_pdb_active check (active_flag in ('Y','N'))
);

create table pdb_project (
    pdb_id              number not null,
    project_id          number not null,
    primary_flag        char(1) default 'N' not null,
    constraint pk_pdb_project primary key (pdb_id, project_id),
    constraint fk_pdbproj_pdb foreign key (pdb_id) references pdb(pdb_id),
    constraint fk_pdbproj_project foreign key (project_id) references project(project_id),
    constraint ck_pdbproj_primary check (primary_flag in ('Y','N'))
);

create unique index uk_pdb_project_primary
    on pdb_project (case when primary_flag = 'Y' then pdb_id end);

create table db_account (
    account_id          number generated by default as identity primary key,
    pdb_id              number not null,
    account_name        varchar2(128) not null,
    account_type        varchar2(20) not null,
    account_status      varchar2(30) not null,
    last_password_change date,
    description         varchar2(500),
    constraint fk_account_pdb foreign key (pdb_id) references pdb(pdb_id),
    constraint uk_pdb_account unique (pdb_id, account_name),
    constraint ck_account_type check (account_type in ('SCHEMA','USER','SERVICE','DBLINK','SHARED'))
);

create table account_project (
    account_id          number not null,
    project_id          number not null,
    primary_flag        char(1) default 'Y' not null,
    constraint pk_account_project primary key (account_id, project_id),
    constraint fk_acctproj_account foreign key (account_id) references db_account(account_id),
    constraint fk_acctproj_project foreign key (project_id) references project(project_id),
    constraint ck_acctproj_primary check (primary_flag in ('Y','N'))
);

create unique index uk_account_project_primary
    on account_project (case when primary_flag = 'Y' then account_id end);

create table db_service (
    service_id          number generated by default as identity primary key,
    pdb_id              number not null,
    service_name        varchar2(128) not null,
    enabled_flag        char(1) default 'Y' not null,
    constraint fk_service_pdb foreign key (pdb_id) references pdb(pdb_id),
    constraint uk_pdb_service unique (pdb_id, service_name),
    constraint ck_service_enabled check (enabled_flag in ('Y','N'))
);

create table service_instance_expectation (
    service_id          number not null,
    instance_id         number not null,
    expected_flag       char(1) default 'Y' not null,
    observed_flag       char(1) default 'N' not null,
    constraint pk_service_instance primary key (service_id, instance_id),
    constraint fk_svci_service foreign key (service_id) references db_service(service_id),
    constraint fk_svci_instance foreign key (instance_id) references db_instance(instance_id),
    constraint ck_svci_expected check (expected_flag in ('Y','N')),
    constraint ck_svci_observed check (observed_flag in ('Y','N'))
);

create table dr_relationship (
    dr_relationship_id  number generated by default as identity primary key,
    primary_cdb_id      number not null,
    standby_cdb_id      number not null,
    protection_mode     varchar2(30),
    transport_status    varchar2(30),
    apply_status        varchar2(30),
    constraint fk_dr_primary_cdb foreign key (primary_cdb_id) references cdb(cdb_id),
    constraint fk_dr_standby_cdb foreign key (standby_cdb_id) references cdb(cdb_id),
    constraint uk_dr_pair unique (primary_cdb_id, standby_cdb_id),
    constraint ck_dr_distinct check (primary_cdb_id <> standby_cdb_id)
);

create table patch_group (
    patch_group_id      number generated by default as identity primary key,
    patch_group_name    varchar2(100) not null,
    target_ru           varchar2(30) not null,
    maintenance_window  varchar2(100),
    constraint uk_patch_group_name unique (patch_group_name)
);

create table cdb_patch_schedule (
    cdb_id              number not null,
    patch_group_id      number not null,
    scheduled_date      date,
    completion_date     date,
    status              varchar2(20) default 'PLANNED' not null,
    constraint pk_cdb_patch_schedule primary key (cdb_id, patch_group_id),
    constraint fk_patch_cdb foreign key (cdb_id) references cdb(cdb_id),
    constraint fk_patch_group foreign key (patch_group_id) references patch_group(patch_group_id),
    constraint ck_patch_status check (status in ('PLANNED','READY','COMPLETE','DEFERRED','FAILED'))
);

create table standard_exception (
    exception_id        number generated by default as identity primary key,
    pdb_id              number,
    cdb_id              number,
    exception_type      varchar2(50) not null,
    description         varchar2(1000) not null,
    justification       varchar2(1000) not null,
    approved_by         varchar2(100),
    review_date         date,
    active_flag         char(1) default 'Y' not null,
    constraint fk_exception_pdb foreign key (pdb_id) references pdb(pdb_id),
    constraint fk_exception_cdb foreign key (cdb_id) references cdb(cdb_id),
    constraint ck_exception_target check (pdb_id is null or cdb_id is null),
    constraint ck_exception_active check (active_flag in ('Y','N'))
);
